source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target '常用控件列表' do

#  pod 'ReactiveCocoa', '~> 8.0.2'
  pod 'ReactiveObjC', '~> 3.1.1'
  #pod 'IJKMediaFramework', '~> 0.1.2'
  pod 'BMLongPressDragCellCollectionView', '~> 3.0.1'
  pod 'Masonry', :git => 'https://github.com/Herbert77/Masonry.git', :inhibit_warnings => true
  pod 'FLAnimatedImage', '~> 1.0.16'
  
end	
